### ISSUE TITLE
Augury stops to work after page refresh.

### ISSUE THREAD

**Issue by Natanael1234** [rangle/augury#422]
After I reload a page Augury stops to works.

I'm working with SystemJS which live updates the application in the browser every time a source code file is saved. 

Also if I reload mannually the page the plugins stops to work. 

It just shows nothing in Component Tree, Properties, etc.

**Comment by igor-ka** [comment]
Hi @Natanael1234 which version of Augury are you using?

**Comment by Natanael1234** [comment]
Version 1.0.1.

**Comment by sumitarora** [comment]
@Natanael1234 Its fixed in the PR https://github.com/rangle/augury/pull/419 should be available in next release

**Comment by Epotignano** [comment]
+1

**Comment by sumitarora** [comment]
Fixed with release 1.0.2 https://github.com/rangle/augury/blob/dev/CHANGELOG.md

**Comment by kirjai** [comment]
Unfortunately, I am still seeing this issue using version 1.0.5. Augury loads without any problems when i open up a new tab and go directly to my application, however if i refresh the page - the Component Tree does not appear anymore. The Router tree is still there though.

Chrome 52.0.2743.116

**Comment by clbond** [comment]
I believe this has been fixed in the latest code. Would you mind checking out the rangle/augury dev branch and run:

```
npm install
npm run build
npm run pack
```

And install the resulting augury.crx file in your browser. If you see a white screen immediately after installing you should restart your browser since I think there may be an issue around installation / first load that I haven't had a chance to look at.
