### ISSUE TITLE
State not visible when injecting router.

### ISSUE THREAD

**Issue by smith64fx** [rangle/augury#699]
Hey guys,
We use Angular 2.0 + ngrx in our app.

For some reason we can not see the local variables of our component when the component gets the Router injected..

Here is an example:

![image](https://cloud.githubusercontent.com/assets/3246782/18843617/0eec6168-841a-11e6-931c-464ee84c6399.png)

**Comment by tiagoroldao** [comment]
This seems to extend to any components that depend on Router, directly or indirectly - if the Router is in the dependency tree state is not visible.

**Comment by stevenkampen** [comment]
@smith64fx Is this still an issue? I've attempted to reproduce it without any luck. I injected the router into a component, and I can see it, plus all other state in the state panel. Can you give it a quick re-test?

**Comment by stevenkampen** [comment]
@tiagoroldao Can you speak to this still being an issue or not?

**Comment by stevenkampen** [comment]
Closing this now with the assumption that it no longer occurs. Please comment if that turns out to not be the case, and we can reopen.

**Comment by Sabartius** [comment]
@stevenkampen This error still occurs, at least for me using Version 1.2.5 of Augury.
I have two Components, which get rendered inside a router-outlet:

- A gets a router injected
- B doesn't get a router injected

When i navigate to Component B, everything is fine, i can see and manipulate the state of the Component.
But when i navigate to Component A, i cannot see the state (and yes it has state!), but i can still see the Providers and Dependencies (which i can see on both Components).

Hope this helps finding the Bug

**Comment by stevenkampen** [comment]
This has been fixed in version 1.2.9 which was just released.

**Comment by amellnik** [comment]
I think this or a similar issue is still present -- after updating to 1.2.9 I still can't see the state for components which have `Router` and `ActivatedRoute` injected.

**Comment by stevenkampen** [comment]
@Sabartius, @amellnik Ok I'll look into this again.

**Comment by stevenkampen** [comment]
@amellnik I am not able to reproduce the issue with your example repo.

<img width="721" alt="screen shot 2017-03-02 at 4 34 52 pm" src="https://cloud.githubusercontent.com/assets/898763/23514006/428e7f5c-ff66-11e6-91bf-f7bbfd8679e2.png">

**Comment by stevenkampen** [comment]
@Sabartius Are you seeing this still? I can't reproduce it it seems. If you can create a single component app where this error exists I'll try again at reproducing it, but for now I'll close this. Thanks.

**Comment by Sabartius** [comment]
@stevenkampen somehow the issue vanished today, and i don't know what i did differently. I'm sorry that i bothered you.

**Comment by Hojou** [comment]
Not sure if i was supposed to just comment here, but i created a new bug here:
https://github.com/rangle/augury/issues/1283
